
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "SNS_NAME" CASCADE CONSTRAINTS;
DROP TABLE "TEACHER" CASCADE CONSTRAINTS;
DROP TABLE "BLACKLIST" CASCADE CONSTRAINTS;
DROP TABLE "ADMIN" CASCADE CONSTRAINTS;
DROP TABLE "GRADE" CASCADE CONSTRAINTS;
DROP TABLE "TOP_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "MID_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "SECTION" CASCADE CONSTRAINTS;
DROP TABLE "SUB_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "MOVIE" CASCADE CONSTRAINTS;

DROP TABLE "GOAL" CASCADE CONSTRAINTS;
DROP TABLE "REQUIREMENT" CASCADE CONSTRAINTS;
DROP TABLE "SUBJECT" CASCADE CONSTRAINTS;
DROP TABLE "CART" CASCADE CONSTRAINTS;
DROP TABLE "WISH" CASCADE CONSTRAINTS;
DROP TABLE "ORDER_SUMMARY" CASCADE CONSTRAINTS;
DROP TABLE "PAYMENT" CASCADE CONSTRAINTS;
DROP TABLE "PAYSTATE" CASCADE CONSTRAINTS;
DROP TABLE "REVIEW" CASCADE CONSTRAINTS;
DROP TABLE "ADMINBOARD" CASCADE CONSTRAINTS;
DROP TABLE "TARGET" CASCADE CONSTRAINTS;

DROP TABLE "TEACHERBOARD" CASCADE CONSTRAINTS;
DROP TABLE "MESSAGE" CASCADE CONSTRAINTS;
DROP TABLE "ORDER_DETAIL" CASCADE CONSTRAINTS;
DROP TABLE "DISCOUNT_LOG" CASCADE CONSTRAINTS;
DROP TABLE "CHARGE" CASCADE CONSTRAINTS;
DROP TABLE "POINT_LOG" CASCADE CONSTRAINTS;
DROP TABLE "POINT" CASCADE CONSTRAINTS;
DROP TABLE "CHAT" CASCADE CONSTRAINTS;